# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 4b76fb66c63a0d434c6c3300b8caf8a7eb66b73fd4135abd44e227e8bda0e528650a85aebc9c140fee2e9a89d7cf3f6e39a50ad3db2fc1d159ac05bca462235e

test:
  domain_name: example.com 
  secret_key_base: 035a3790eaadf704a6f1d755c00ea1b87c140435f795ab8ecf5f0edf8b163b68a8d58456852c161e563b7352405946e3fe853255661f0a3d2754803b2e6c88d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
